# Generated by Django 5.0 on 2023-12-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserEmail', models.EmailField(max_length=254, unique=True)),
                ('UserPassword', models.CharField(default='default_password_hash', max_length=128)),
                ('UserDefaultSign', models.CharField(max_length=500)),
            ],
        ),
    ]
